const router = require("express").Router();
const controllers = require("../controllers/dishes");
const verifyToken = require("../middlewares/verifyToken");
const upload = require("../middlewares/upload");
router.get("/getAvailableDishes", controllers.getAvailableDishes);
router.get("/getAllDishes", verifyToken, controllers.getAllDishes);
router.get("/getNotAvailableDishes",verifyToken,controllers.getNotAvailableDishes);
router.post("/addDish", verifyToken, upload.single("image"), controllers.addDish);
router.delete("/deleteDish", verifyToken, controllers.deleteDish);
router.put("/Available", verifyToken, controllers.Available);
router.put("/NotAvailable", verifyToken, controllers.NotAvailable);
router.put("/updateImage", verifyToken, upload.single("image"), controllers.updateImage);
router.put("/updatePrice", verifyToken, controllers.updatePrice);
router.put("/updateDescription", verifyToken, controllers.updateDescription);
router.put("/updateName", verifyToken, controllers.updateName);
module.exports = router;
